### ISSUE TITLE
Not compatible with Gradle 8.0

### ISSUE THREAD

**Issue by jpdup** [ivancarras/graphfity#1]
I'm getting these runtime error. 
```Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.```

**Comment by ivancarras** [comment]
@jpdup Thanks for the prompt, I'll update it in future releases :)

**Comment by ivancarras** [comment]
@jpdup Keep posted this feature will be compatible in the next Graphfity version 1.1.0
